server:
  port: 9090
spring:
  main:
    web-application-type: reactive
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: rootPassword
    username: root
    url: jdbc:mysql://localhost:3306/hospital_management

  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/authenticate/**,/refreshToken/**
        - id: sample-api
          uri: http://localhost:8086
          predicates:
            - Path=/role/**,/doctor/**,/privileges/**